### ISSUE TITLE
The build command makes assumptions about how to include dependnecies.

### ISSUE THREAD

**Issue by niall-mediasuite** [lucasvieirasilva/nx-plugins#23]
- [ ] I'd be willing to implement this feature *My current time commitments within my organisation will potentially limit my involvement. I do have some time at the moment to work on this but other priorities may change things.*

## Description

I'm currently looking to use this plugin to manage internal libraries within our organisation. The structure is such that we have some base libraries that most other libraries depend on and then we have applications. We don't plan on storing the applications within the nx monorepo, only the libraries. Therefore libraries will need to be built and pushed to a pypi registry to be consumed by our applications.

The current challenge I have is that because some of the libraries depend on other libraries the current implementation of this plugin results in the whole code from the base library being included in the higher level library.

The other thing I have noticed is that version numbers get re-written with specific values. Instead of the original dependency requirements such as `=~2.3.0` being included, they get overridden with the values from the lock file.

## Motivation

This behaviour would be beneficial because I think it results in a simpler implementation that could be useful for many members of the Python community, my organisation included.

## Suggested Implementation

Ideally for our use case the implementation would be a lot simpler. Instead of copying in local dependencies they would be added as normal dependencies by looking up the package name in the `pyproject.toml` then injecting the current version from the `pyproject.toml` or using a configured version string e.g. `=~2.1.0`.

I'm not sure how to handle the current implementation. It could either be implemented as an arg / config option on the current build command or added as a new command all together. I have prototyped what would be required for the solution I suggested and it makes most of the current build command redundant.

I have created [a branch here](https://github.com/niall-mediasuite/nx-plugins/tree/simplify-build-command) which supports the changes I have addressed but at the expense of all currently functionality. I don't expect it to be used in its current state but as a tool for me to test and to provide context on the changes I'm requesting.

**Comment by lucasvieirasilva** [comment]
@niall-mediasuite the current approach is useful when you deploy as an application such as (serverless lambda functions or docker) because you ensure the dependencies stay with the same versions that you previously tested, preventing productions issues because a dependency of a dependency release a broken version.
However, when you need to publish the library to a PyPi repository is good to have the dependency version as a range to avoid conflicts with who installs it as a dependency.
I think we should parametrize this behavior to work for both scenarios as you also suggested.

**Comment by niall-mediasuite** [comment]
Thanks @lucasvieirasilva I really appreciate your responsiveness.

I can see how that would be the case. I'm wondering if it might make the code less complex to just create two build commands that can be enabled as required rather than try to include the functionality in a single command.

Thanks for having a go at implementing. Unfortunately I can't spend any time outside of my work hours on this, but if you are able to implement this in the next few days I can test and make and changes if require next week.

Let me know if you need any clarity from me and I'll get back to you asap.

**Comment by lucasvieirasilva** [comment]
@niall-mediasuite I got some free time this month, and I'm using it to work on this project to make it better for the community.

well, I'll see if it is necessary to split it into two commands, I'll think of a way to make it simple to understand.

about the build command, the current approach uses the locked versions across all the dependencies and bundles the local dependencies in the same wheel file, like this:

`proj1` depends on a local project named `lib1` and `lib1` depends on an external package called `pendulum`.

With the current approach, the build command includes the code and brings all the external dependencies to the build package, like the following example:

```toml
[tool.poetry]
name = "pymonorepo-proj1"

  [[tool.poetry.packages]]
  include = "pymonorepo_proj1"

  [tool.poetry.dependencies]
  python = ">=3.8,<3.10"
  pendulum = "^2.1.2"

    [tool.poetry.dependencies.pymonorepo-lib1]
    path = "../lib1"
    develop = true
```

and

```toml
[tool.poetry]
name = "pymonorepo-lib1"
version = "1.0.0"

  [[tool.poetry.packages]]
  include = "pymonorepo_lib1"

  [tool.poetry.dependencies]
  python = ">=3.8,<3.10"
  numpy = "^1.24.1"
```

After the build the temporary `pyproject` looks this way:

```toml
[tool.poetry]
name = "pymonorepo-proj1"
version = "1.0.0"

  [[tool.poetry.packages]]
  include = "pymonorepo_proj1"

  [[tool.poetry.packages]]
  include = "pymonorepo_lib1"

  [tool.poetry.dependencies]
  python = ">=3.8,<3.10"

    [tool.poetry.dependencies.numpy]
    version = "1.24.1 "
    markers = 'python_version >= "3.8" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.pendulum]
    version = "2.1.2 "
    markers = 'python_version >= "3.8" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.python-dateutil]
    version = "2.8.2 "
    markers = 'python_version >= "3.8" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.pytzdata]
    version = "2020.1 "
    markers = 'python_version >= "3.8" and python_version < "3.10"'
    optional = false

    [tool.poetry.dependencies.six]
    version = "1.16.0 "
    markers = 'python_version >= "3.8" and python_version < "3.10"'
    optional = false
```

Note, that `python-dateutil` is a dependency of `pendulum`, and the `pymonorepo_lib1` is now part of the project instead of a dependency.

By adding a new behavior to this process, I see two different related behaviors that in my opinion should be implemented.

1. Still bundling the local dependencies together and bringing their dependencies but in the same way.

Let's consider the sample example, the temporary `pyproject` looks this way:

```toml
[tool.poetry]
name = "pymonorepo-proj1"
version = "1.0.0"

  [[tool.poetry.packages]]
  include = "pymonorepo_proj1"

  [[tool.poetry.packages]]
  include = "pymonorepo_lib1"

  [tool.poetry.dependencies]
  python = ">=3.8,<3.10"
  numpy = "^1.24.1"
  pendulum = "^2.1.2"
```

Note, the `pymonorepo_lib1` stills bundled in the project but the dependencies are listed in the same way it is on the `pyproject` (using `^`).

2. Referencing local dependencies using their versions (this behavior requires the local dependencies to be published as well)

```toml
[tool.poetry]
name = "pymonorepo-proj1"
version = "1.0.0"

  [[tool.poetry.packages]]
  include = "pymonorepo_proj1"

  [tool.poetry.dependencies]
  python = ">=3.8,<3.10"
  pendulum = "^2.1.2"
  pymonorepo-lib1 = "1.0.0"
```

If all the local dependency trees are going to be published to the pypi repository the second approach is better because it uses the standard pip dependency resolution.

If the local dependencies are designed to be only workspace dependencies and don't need to be published to the pypi repository the first approach is better because bundles the local dependencies.

I'm thinking to implement both approaches by adding 2 options in the executor `lockedVersions` (default `true`) and `bundleLocalDependencies` (default `true`), those options can be configured in the `project.json`like this:

```json
{
  "name": "lib1",
  "targets": {
    "build": {
      "executor": "@nxlv/python:build",
      "outputs": ["packages/lib1/dist"],
      "options": {
        "outputPath": "packages/lib1/dist",
        "lockedVersions": "false",
        "bundleLocalDependencies": "false"
      }
    }
  },
  "tags": []
}
```

or through CLI `npx nx run lib:build --lockedVersions=false --bundleLocalDependencies=false` (if you already configured in the project.json you don't need to provide those CLI options).

However, might have some cases in which some local dependencies need to be resolved as the standard version and some others as a bundle.

For this scenario, I'm planning to use a property in the build execution inside the `project.json` to identify if that project is marked to be published or not, if yes only reference the version, if no bundle the project.

The logic above is only required if the `bundleLocalDependencies` is set to `false`.

`packages/lib1/project.json`
```json
{
  "name": "lib1",
  "targets": {
    "build": {
      "executor": "@nxlv/python:build",
      "outputs": ["packages/lib1/dist"],
      "options": {
        "outputPath": "packages/lib1/dist",
        "publish": true,
        "lockedVersions": "false",
        "bundleLocalDependencies": "false"
      }
    }
  },
  "tags": []
}
```

For the example above if the `bundleLocalDependencies` is set to `false` the built pyproject will be in this way:

```toml
[tool.poetry]
name = "pymonorepo-proj1"
version = "1.0.0"

  [[tool.poetry.packages]]
  include = "pymonorepo_proj1"

  [tool.poetry.dependencies]
  python = ">=3.8,<3.10"
  pendulum = "^2.1.2"
  pymonorepo-lib1 = "1.0.0"
```

if the `publish` property is set to `false`, it will be in this way:

```toml
[tool.poetry]
name = "pymonorepo-proj1"
version = "1.0.0"

  [[tool.poetry.packages]]
  include = "pymonorepo_proj1"

  [[tool.poetry.packages]]
  include = "pymonorepo_lib1"

  [tool.poetry.dependencies]
  python = ">=3.8,<3.10"
  numpy = "^1.24.1"
  pendulum = "^2.1.2"
```

Could you give me your opinion about this design?
